### ISSUE TITLE
elsa3.0

### ISSUE THREAD

**Issue by askdong** [jxnkwlp/abp-elsa-module#105]
when elsa3.0 will be integrated？we hope that.

**Comment by jxnkwlp** [comment]
In plan, will be start integration in Q3

**Comment by XuJin186** [comment]
elsa3  外部依赖很多  假如还是按照你现在所做的工作  基本上都是属于重写了elsa设计器和接口 存储部分了

**Comment by jxnkwlp** [comment]
> elsa3 外部依赖很多 假如还是按照你现在所做的工作 基本上都是属于重写了elsa设计器和接口 存储部分了

差不多是的。

**Comment by XuJin186** [comment]
> > elsa3 外部依赖很多 假如还是按照你现在所做的工作 基本上都是属于重写了elsa设计器和接口 存储部分了
> 
> 差不多是的。

那岂不是没办法享受原仓库升级带来的好处了  其实我也考虑了很多  似乎都没有好的解决方案 只能去重写

**Comment by jxnkwlp** [comment]
> > > elsa3 外部依赖很多 假如还是按照你现在所做的工作 基本上都是属于重写了elsa设计器和接口 存储部分了
> > 
> > 
> > 差不多是的。
> 
> 那岂不是没办法享受原仓库升级带来的好处了 其实我也考虑了很多 似乎都没有好的解决方案 只能去重写

嗯。 从版本号来看，大版本升级为3，可以不兼容旧的。 （当然，如果能兼容最好）

**Comment by XuJin186** [comment]
请问有具体计划嘛 想一起参与编写

**Comment by jxnkwlp** [comment]
> 请问有具体计划嘛 想一起参与编写

目前有个大概，还没有细化。 我建立了个QQ群 (813241631)，如有兴趣，可以加入一起探讨。
