### ISSUE TITLE
支持代码定义工作流吗

### ISSUE THREAD

**Issue by WeiJunFenYou** [jxnkwlp/abp-elsa-module#12]
而非用流程设计器定义

**Comment by jxnkwlp** [comment]
暂时还不兼容。
因为默认情况下生成的 activity id 是 `activity-1``activity-2` 这种格式，但是这里要求id是`Guid`类型。
当然如果重写部分类使其生成Guid类型的Id的话，就能兼容了。

[activityBuilder.ActivityId = string.IsNullOrWhiteSpace(activityId) ? $"{activityIdPrefix}-{++index}" : $"{activityIdPrefix}-{activityId}";](https://github.com/elsa-workflows/elsa-core/blob/86de5d3e1bb6df970bf5bc60d7483530f744e09e/src/core/Elsa.Core/Builders/CompositeActivityBuilder.cs#L202)
