### ISSUE TITLE
 Host terminated unexpectedly!

### ISSUE THREAD

**Issue by iddelacruz** [jxnkwlp/abp-elsa-module#4]
Hi, I am trying to run your package and got this error:
`Volo.Abp.AbpInitializationException: An error occurred during ConfigureServicesAsync phase of the module Passingwind.Abp.ElsaModule.ElsaModuleDomainModule, Passingwind.Abp.ElsaModule.Domain, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null. See the inner exception for details.
 ---> System.TypeLoadException: Method 'FindManyAsync' in type 'Passingwind.Abp.ElsaModule.Stores.WorkflowInstanceStore' from assembly 'Passingwind.Abp.ElsaModule.Domain, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
`

**Comment by jxnkwlp** [comment]
which version you install ?  abp and elsa .

**Comment by iddelacruz** [comment]
I keep the same version you have in your project.

**Comment by jxnkwlp** [comment]
The issue happened by elsa version 2.9 , and the master branch has been updated , but have not publish the new nuget package .

I will publish new nuget package by later .   

regards.
