### ISSUE TITLE
Business flow design

### ISSUE THREAD

**Issue by jxnkwlp** [jxnkwlp/abp-elsa-module#47]
Generally, business processes will include forms and business state changes. 

example, in financial approval, has some points:

1. user request and fill an form and explain what todo
2. the user of financial role can be approval or not and can see the forms information that the user request
3. request user can view the request in any time and can know the current busines state
4. has some logic or condition in steps and steps
5. use rest api to interact with outer system 

For implement this, has big functions: 

- Forms 
- Business flow

## Forms

Forms definition an form for end user to use. can fill or view data . can definition fields and process state.

## Business flow

Business flow will be link forms and workflow, include security options, process flow state and so on.

**Comment by jxnkwlp** [comment]
#5

**Comment by askdong** [comment]
it will be a big project

**Comment by jxnkwlp** [comment]
Will be split into small functions
