### ISSUE TITLE
第三方组件

### ISSUE THREAD

**Issue by XuJin186** [jxnkwlp/abp-elsa-module#8]
elsa集成了很多得第三方组件,比如automapping   容易和abp的起冲突

**Comment by jxnkwlp** [comment]
这个没有很好的办法处理，并且 automapping 小版本更新有的时候也有 break changes 。

**Comment by XuJin186** [comment]
独立部署应该还行   我也在考虑这个怎么实现 ,,,,,,,,哈哈  到处抄
