### ISSUE TITLE
web启动报错

### ISSUE THREAD

**Issue by seamusic** [jxnkwlp/abp-elsa-module#9]
先启动 Passingwind.WorkflowApp.HttpApi.Host，再启动 Passingwind.WorkflowApp.Web，报错：
![image](https://user-images.githubusercontent.com/172009/219869163-81586ae1-be47-43c8-99cd-b1461f1e9a03.png)
修改了host的数据库链接，使用两个站点都是用同样的数据库AbpElsaDemo。
请问，要怎么样才能让web启动起来呢？

**Comment by jxnkwlp** [comment]
1.  Passingwind.WorkflowApp.HttpApi.Host 在demo这里无需启动。
2.  该错误是前端产物不存在，可以从 Release 下载最的前端代码，比如 [workflow-dashboard.zip](https://github.com/jxnkwlp/abp-elsa-module/releases/download/v0.9.0%2B581faf15/workflow-dashboard.zip) ，放到 Web 项目 wwwroot 下的 dist 目录，再次启动即可。
